# Generated by Django 4.2.5 on 2023-10-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productthumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productthumbnail',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='ProductThumbnail',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.productthumbnail'),
            preserve_default=False,
        ),
    ]
