# Generated by Django 4.2.5 on 2023-10-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='thump_nail',
        ),
    ]
