# Generated by Django 4.2.5 on 2023-10-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_images_product_thump_nail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductThumpNail',
        ),
    ]
