# Generated by Django 4.2.5 on 2023-10-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_productimage_productthumpnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productthumpnail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_thump_nails', to='shop.product'),
        ),
    ]
