# Generated by Django 4.2.5 on 2023-10-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_thump_nail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productthumpnail',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='quantinty',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
