# Generated by Django 4.2.5 on 2023-10-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_productthumpnail_product_product_quantinty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productthumpnail',
            name='product',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='product_thump_nails', to='shop.product'),
            preserve_default=False,
        ),
    ]
