# Generated by Django 4.2.5 on 2023-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productthumpnail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productthumpnail',
            name='image',
            field=models.FileField(upload_to='products/%Y/%m/%d'),
        ),
    ]
