# Generated by Django 4.2.5 on 2023-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productthumpnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productthumpnail',
            name='product',
        ),
        migrations.AlterField(
            model_name='productthumpnail',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
