# Generated by Django 4.2.5 on 2023-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_productthumpnail_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thump_nail',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, related_name='product_thumbnails', to='shop.productthumpnail'),
        ),
    ]
