# Generated by Django 4.2.5 on 2023-10-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_thumbnails_productthumpnail_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductThumpNail',
        ),
    ]
