# Generated by Django 4.2.5 on 2023-10-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_delete_productthumpnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumpNail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_thump_nails', to='shop.product')),
            ],
        ),
    ]
